# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  main: ./cmd/test-cli/main.go
  binary: test-cli
archive:
  replacements:
    darwin: Darwin
    windows: Windows
    linux: Linux
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
brew:
  name: test-cli

  # Reporitory to push the tap to.
  github:
    owner: jorgeacetozi
    name: homebrew-test-cli

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's homepage.
  # Default is empty.
  homepage: "https://jorgeacetozi.com/"

  # Your app's description.
  # Default is empty.
  description: "Simple test CLI in Go."

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # Default is false.
  skip_upload: true

  # So you can `brew test` your formula.
  # Default is empty.
  test: |
    system "#{bin}/program version"
