builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  main: ./cmd/test-cli/main.go
  binary: test-cli
archive:
  replacements:
    darwin: Darwin
    windows: Windows
    linux: Linux
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
brew:
  name: test-cli
  github:
    owner: outlyerapp
    name: homebrew-tap
  folder: Formula
  homepage: "https://jorgeacetozi.com/"
  description: "Simple test CLI in Go."
  skip_upload: true
